package com.csci2020.frontend;

import java.awt.*;
import java.util.Objects;

public class NewTheme {
    // The LIGHT and DARK theme color codes were generated by Claude Haiku 4.5 based on Material Design Guidelines
    public static final NewTheme LIGHT = new ThemeBuilder()
            .setBackgroundPrimary(Color.decode("#FFFBFE"))
            .setSurfacePrimary(Color.decode("#FEF7FF"))
            .setSurfaceSecondary(Color.decode("#F3E5F5"))
            .setForegroundPrimary(Color.decode("#1C1B1F"))
            .setForegroundSecondary(Color.decode("#49454E"))
            .setForegroundDisabled(Color.decode("#B3B0B7"))
            .setBorderPrimary(Color.decode("#E0E0E0"))
            .setBorderFocused(Color.decode("#6750A4"))
            .setDivider(Color.decode("#E8E0E8"))
            .setButtonBackground(Color.decode("#6750A4"))
            .setButtonHover(Color.decode("#EADDFF"))
            .setButtonPressed(Color.decode("#5A4481"))
            .setButtonForeground(Color.decode("#FFFFFF"))
            .setInputBackground(Color.decode("#FFFBFE"))
            .setInputForeground(Color.decode("#1C1B1F"))
            .setInputPlaceholder(Color.decode("#9B98A3"))
            .setError(Color.decode("#B3261E"))
            .setSuccess(Color.decode("#1B5E20"))
            .setWarning(Color.decode("#F57C00"))
            .setInfo(Color.decode("#0D47A1"))
            .build();


    public static NewTheme DARK = new ThemeBuilder()
            .setBackgroundPrimary(Color.decode("#121212"))
            .setSurfacePrimary(Color.decode("#1E1E1E"))
            .setSurfaceSecondary(Color.decode("#2A2A2A"))
            .setForegroundPrimary(Color.decode("#E6E1E5"))
            .setForegroundSecondary(Color.decode("#CAC4CF"))
            .setForegroundDisabled(Color.decode("#938F99"))
            .setBorderPrimary(Color.decode("#3F3F3F"))
            .setBorderFocused(Color.decode("#D0BCFF"))
            .setDivider(Color.decode("#424242"))
            .setButtonBackground(Color.decode("#6750A4"))
            .setButtonHover(Color.decode("#7961B4"))
            .setButtonPressed(Color.decode("#8977C9"))
            .setButtonForeground(Color.decode("#FFFFFF"))
            .setInputBackground(Color.decode("#2B2B2B"))
            .setInputForeground(Color.decode("#E6E1E5"))
            .setInputPlaceholder(Color.decode("#9B98A3"))
            .setError(Color.decode("#F2B8B5"))
            .setSuccess(Color.decode("#81C784"))
            .setWarning(Color.decode("#FFB74D"))
            .setInfo(Color.decode("#90CAF9"))
            .build();

    // The DRACULA color codes were created using the Dracula specification (https://draculatheme.com/spec)
    public static NewTheme DRACULA = new ThemeBuilder()
            .setBackgroundPrimary(Color.decode("#282A36"))
            .setSurfacePrimary(Color.decode("#343746"))
            .setSurfaceSecondary(Color.decode("#424450"))
            .setForegroundPrimary(Color.decode("#F8F8F2"))
            .setForegroundSecondary(Color.decode("#6272A4"))
            .setForegroundDisabled(Color.decode("#6272A4"))
            .setBorderPrimary(Color.decode("#404450"))
            .setBorderFocused(Color.decode("#BD93F9"))
            .setDivider(Color.decode("#404450"))
            .setButtonBackground(Color.decode("#343746"))
            .setButtonHover(Color.decode("#232730"))
            .setButtonPressed(Color.decode("#21222C"))
            .setButtonForeground(Color.decode("#F8F8F2"))
            .setInputBackground(Color.decode("#343746"))
            .setInputForeground(Color.decode("#F8F8F2"))
            .setInputPlaceholder(Color.decode("#606371"))
            .setError(Color.decode("#FF5555"))
            .setSuccess(Color.decode("#50FA7B"))
            .setWarning(Color.decode("#F1FA8C"))
            .setInfo(Color.decode("#FFB86C"))
            .buildOrDefault(NewTheme.DARK);

    private static NewTheme activeTheme = NewTheme.DRACULA;
    public static void setActiveTheme(NewTheme theme){
        activeTheme = theme;
    }
    public static NewTheme getActiveTheme(){
        return activeTheme;
    }

    private final Color backgroundPrimary, surfacePrimary, surfaceSecondary;
    private final Color foregroundPrimary, foregroundSecondary, foregroundDisabled;
    private final Color borderPrimary;
    private final Color borderFocused;
    private final Color divider;
    private final Color buttonBackground, buttonHover, buttonPressed, buttonForeground;
    private final Color inputBackground, inputForeground, inputPlaceholder;
    private final Color error, success, warning, info;

    public NewTheme(Color backgroundPrimary, Color surfacePrimary, Color surfaceSecondary,
                    Color foregroundPrimary, Color foregroundSecondary, Color foregroundDisabled,
                    Color borderPrimary, Color borderFocused, Color divider,
                    Color buttonBackground, Color buttonHover, Color buttonPressed, Color buttonForeground,
                    Color inputBackground, Color inputForeground, Color inputPlaceholder,
                    Color error, Color success, Color warning, Color info) {
        this.backgroundPrimary = backgroundPrimary;
        this.surfacePrimary = surfacePrimary;
        this.surfaceSecondary = surfaceSecondary;
        this.foregroundPrimary = foregroundPrimary;
        this.foregroundSecondary = foregroundSecondary;
        this.foregroundDisabled = foregroundDisabled;
        this.borderPrimary = borderPrimary;
        this.borderFocused = borderFocused;
        this.divider = divider;
        this.buttonBackground = buttonBackground;
        this.buttonHover = buttonHover;
        this.buttonPressed = buttonPressed;
        this.buttonForeground = buttonForeground;
        this.inputBackground = inputBackground;
        this.inputForeground = inputForeground;
        this.inputPlaceholder = inputPlaceholder;
        this.error = error;
        this.success = success;
        this.warning = warning;
        this.info = info;
    }

    public static class ThemeBuilder {
        private Color backgroundPrimary, surfacePrimary, surfaceSecondary;
        private Color foregroundPrimary, foregroundSecondary, foregroundDisabled;
        private Color borderPrimary, borderFocused, divider;
        private Color buttonBackground, buttonHover, buttonPressed, buttonForeground;
        private Color inputBackground, inputForeground, inputPlaceholder;
        private Color error, success, warning, info;
        public ThemeBuilder() {

        }

        /**
         * Builds the theme using set values, or values copied from {@link NewTheme#LIGHT} if unset.
         * @return Built theme
         */
        public NewTheme buildOrDefault(NewTheme defaultTheme) {
            return new NewTheme(
                    backgroundPrimary != null ? backgroundPrimary : defaultTheme.getBackgroundPrimary(),
                    surfacePrimary != null ? surfacePrimary : defaultTheme.getSurfacePrimary(),
                    surfaceSecondary != null ? surfaceSecondary : defaultTheme.getSurfaceSecondary(),
                    foregroundPrimary != null ? foregroundPrimary : defaultTheme.getForegroundPrimary(),
                    foregroundSecondary != null ? foregroundSecondary : defaultTheme.getForegroundSecondary(),
                    foregroundDisabled != null ? foregroundDisabled : defaultTheme.getForegroundDisabled(),
                    borderPrimary != null ? borderPrimary : defaultTheme.getBorderPrimary(),
                    borderFocused != null ? borderFocused : defaultTheme.getBorderFocused(),
                    divider != null ? divider : defaultTheme.getDivider(),
                    buttonBackground != null ? buttonBackground : defaultTheme.getButtonBackground(),
                    buttonHover != null ? buttonHover : defaultTheme.getButtonHover(),
                    buttonPressed != null ? buttonPressed : defaultTheme.getButtonPressed(),
                    buttonForeground != null ? buttonForeground : defaultTheme.getButtonForeground(),
                    inputBackground != null ? inputBackground : defaultTheme.getInputBackground(),
                    inputForeground != null ? inputForeground : defaultTheme.getInputForeground(),
                    inputPlaceholder != null ? inputPlaceholder : defaultTheme.getInputPlaceholder(),
                    error != null ? error : defaultTheme.getError(),
                    success != null ? success : defaultTheme.getSuccess(),
                    warning != null ? warning : defaultTheme.getWarning(),
                    info != null ? info : defaultTheme.getInfo()
            );
        }

        /**
         * Builds the theme using set values. Ensure that all fields are set before calling this,
         * and prefer {@link ThemeBuilder#buildOrDefault(NewTheme)} when possible.
         * @return Built theme
         */
        private NewTheme build(){
            return new NewTheme(
                    Objects.requireNonNull(backgroundPrimary, "backgroundPrimary must not be null"),
                    Objects.requireNonNull(surfacePrimary, "surfacePrimary must not be null"),
                    Objects.requireNonNull(surfaceSecondary, "surfaceSecondary must not be null"),
                    Objects.requireNonNull(foregroundPrimary, "foregroundPrimary must not be null"),
                    Objects.requireNonNull(foregroundSecondary, "foregroundSecondary must not be null"),
                    Objects.requireNonNull(foregroundDisabled, "foregroundDisabled must not be null"),
                    Objects.requireNonNull(borderPrimary, "borderPrimary must not be null"),
                    Objects.requireNonNull(borderFocused, "borderFocused must not be null"),
                    Objects.requireNonNull(divider, "divider must not be null"),
                    Objects.requireNonNull(buttonBackground, "buttonBackground must not be null"),
                    Objects.requireNonNull(buttonHover, "buttonHover must not be null"),
                    Objects.requireNonNull(buttonPressed, "buttonPressed must not be null"),
                    Objects.requireNonNull(buttonForeground, "buttonForeground must not be null"),
                    Objects.requireNonNull(inputBackground, "inputBackground must not be null"),
                    Objects.requireNonNull(inputForeground, "inputForeground must not be null"),
                    Objects.requireNonNull(inputPlaceholder, "inputPlaceholder must not be null"),
                    Objects.requireNonNull(error, "error must not be null"),
                    Objects.requireNonNull(success, "success must not be null"),
                    Objects.requireNonNull(warning, "warning must not be null"),
                    Objects.requireNonNull(info, "info must not be null")
            );
        }
        public ThemeBuilder setBackgroundPrimary(Color backgroundPrimary) {
            this.backgroundPrimary = backgroundPrimary;
            return this;
        }

        public ThemeBuilder setSurfacePrimary(Color surfacePrimary) {
            this.surfacePrimary = surfacePrimary;
            return this;
        }

        public ThemeBuilder setSurfaceSecondary(Color surfaceSecondary) {
            this.surfaceSecondary = surfaceSecondary;
            return this;
        }

        public ThemeBuilder setForegroundPrimary(Color foregroundPrimary) {
            this.foregroundPrimary = foregroundPrimary;
            return this;
        }

        public ThemeBuilder setForegroundSecondary(Color foregroundSecondary) {
            this.foregroundSecondary = foregroundSecondary;
            return this;
        }

        public ThemeBuilder setForegroundDisabled(Color foregroundDisabled) {
            this.foregroundDisabled = foregroundDisabled;
            return this;
        }

        public ThemeBuilder setBorderPrimary(Color borderPrimary) {
            this.borderPrimary = borderPrimary;
            return this;
        }

        public ThemeBuilder setBorderFocused(Color borderFocused) {
            this.borderFocused = borderFocused;
            return this;
        }

        public ThemeBuilder setDivider(Color divider) {
            this.divider = divider;
            return this;
        }

        public ThemeBuilder setButtonBackground(Color buttonBackground) {
            this.buttonBackground = buttonBackground;
            return this;
        }

        public ThemeBuilder setButtonHover(Color buttonHover) {
            this.buttonHover = buttonHover;
            return this;
        }

        public ThemeBuilder setButtonPressed(Color buttonPressed) {
            this.buttonPressed = buttonPressed;
            return this;
        }

        public ThemeBuilder setButtonForeground(Color buttonForeground) {
            this.buttonForeground = buttonForeground;
            return this;
        }

        public ThemeBuilder setInputBackground(Color inputBackground) {
            this.inputBackground = inputBackground;
            return this;
        }

        public ThemeBuilder setInputForeground(Color inputForeground) {
            this.inputForeground = inputForeground;
            return this;
        }

        public ThemeBuilder setInputPlaceholder(Color inputPlaceholder) {
            this.inputPlaceholder = inputPlaceholder;
            return this;
        }

        public ThemeBuilder setError(Color error) {
            this.error = error;
            return this;
        }

        public ThemeBuilder setSuccess(Color success) {
            this.success = success;
            return this;
        }

        public ThemeBuilder setWarning(Color warning) {
            this.warning = warning;
            return this;
        }

        public ThemeBuilder setInfo(Color info) {
            this.info = info;
            return this;
        }
    }
    public Color getBackgroundPrimary() {
        return backgroundPrimary;
    }

    public Color getSurfacePrimary() {
        return surfacePrimary;
    }

    public Color getSurfaceSecondary() {
        return surfaceSecondary;
    }

    public Color getForegroundPrimary() {
        return foregroundPrimary;
    }

    public Color getForegroundSecondary() {
        return foregroundSecondary;
    }

    public Color getForegroundDisabled() {
        return foregroundDisabled;
    }

    public Color getBorderPrimary() {
        return borderPrimary;
    }

    public Color getBorderFocused() {
        return borderFocused;
    }

    public Color getDivider() {
        return divider;
    }

    public Color getButtonBackground() {
        return buttonBackground;
    }

    public Color getButtonHover() {
        return buttonHover;
    }

    public Color getButtonPressed() {
        return buttonPressed;
    }

    public Color getButtonForeground() {
        return buttonForeground;
    }

    public Color getInputBackground() {
        return inputBackground;
    }

    public Color getInputForeground() {
        return inputForeground;
    }

    public Color getInputPlaceholder() {
        return inputPlaceholder;
    }

    public Color getError() {
        return error;
    }

    public Color getSuccess() {
        return success;
    }

    public Color getWarning() {
        return warning;
    }

    public Color getInfo() {
        return info;
    }
}
